/**
 * better-auth, configured for this Worker.
 *
 * Users, accounts and verification rows live in D1 (better-auth >= 1.5 takes
 * the binding directly); live sessions and the auth rate limiter live in KV,
 * where a per-request read does not spend D1's budget. The schema these
 * tables follow is generated by `@better-auth/cli generate` against
 * worker/auth-cli.ts — KEEP THAT STUB'S PLUGIN LIST IN LOCKSTEP with the
 * plugins below, or the generated migrations will silently miss columns.
 *
 * Everything degrades by configuration, matching the rest of this Worker:
 * no GOOGLE_* secrets = no Google button server-side; no TURNSTILE_SECRET =
 * no captcha check (local dev); no SEND_EMAIL binding = verification and
 * reset emails are skipped (see mail.ts). Auth itself works in every case.
 */
import { betterAuth } from 'better-auth';
import { admin, captcha } from 'better-auth/plugins';
import type { D1Database } from '@cloudflare/workers-types';
import { sendMail, type MailBindings } from './mail';

/** Narrow KV shape — same discipline as the other bindings in index.ts. */
export interface SessionsKV {
  get(key: string): Promise<string | null>;
  put(key: string, value: string, opts?: { expirationTtl?: number }): Promise<void>;
  delete(key: string): Promise<void>;
}

export interface AuthBindings extends MailBindings {
  DB: D1Database;
  KV_SESSIONS?: SessionsKV;
  /** The origin users hit. Cookies, callbacks and CSRF trust all key off it. */
  AUTH_ORIGIN?: string;
  BETTER_AUTH_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  TURNSTILE_SECRET?: string;
}

/** better-auth's SecondaryStorage over a KV namespace. */
function kvStorage(kv: SessionsKV) {
  return {
    get: (key: string) => kv.get(key),
    set: async (key: string, value: string, ttl?: number) => {
      await kv.put(key, value, ttl ? { expirationTtl: Math.max(ttl, 60) } : undefined);
    },
    delete: (key: string) => kv.delete(key),
    // One-time reads (verification values). KV cannot do this atomically; the
    // read-then-delete race window is milliseconds and the values are
    // single-use secrets already bound to a user — acceptable.
    getAndDelete: async (key: string) => {
      const value = await kv.get(key);
      if (value !== null) await kv.delete(key);
      return value;
    },
    // Counter with TTL-on-create semantics (the contract better-auth's rate
    // limiter documents): the window is fixed from first increment, stored in
    // the value itself because KV cannot report a key's remaining TTL.
    increment: async (key: string, ttl: number) => {
      const now = Date.now();
      let n = 1;
      let resetAt = now + ttl * 1000;
      const raw = await kv.get(key);
      if (raw !== null) {
        try {
          const prev = JSON.parse(raw) as { n?: number; resetAt?: number };
          if (typeof prev.resetAt === 'number' && prev.resetAt > now) {
            n = (typeof prev.n === 'number' ? prev.n : 0) + 1;
            resetAt = prev.resetAt;
          }
        } catch {
          /* corrupt counter = fresh window */
        }
      }
      const remaining = Math.max(60, Math.ceil((resetAt - now) / 1000));
      await kv.put(key, JSON.stringify({ n, resetAt }), { expirationTtl: remaining });
      return n;
    },
  };
}

function buildAuth(env: AuthBindings) {
  const origin = env.AUTH_ORIGIN || 'http://localhost:4332';
  const google =
    env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET
      ? { google: { clientId: env.GOOGLE_CLIENT_ID, clientSecret: env.GOOGLE_CLIENT_SECRET } }
      : {};

  return betterAuth({
    database: env.DB as never,
    baseURL: origin,
    secret: env.BETTER_AUTH_SECRET,
    trustedOrigins: [origin],

    // Sessions in KV: validated on nearly every request, so they must not
    // spend D1 reads. KV's minimum TTL is 60 s and better-auth passes shorter
    // ones — the clamps are load-bearing, not defensive. KV also has no
    // atomic operations, so getAndDelete and increment are best-effort
    // read-modify-write: good enough for one-time tokens and the auth rate
    // limiter. The endpoint that spends money (/api/ask) keeps its own
    // ATOMIC D1 limiter (bumpLimit) and never relies on this one.
    secondaryStorage: env.KV_SESSIONS ? kvStorage(env.KV_SESSIONS) : undefined,

    emailAndPassword: {
      enabled: true,
      // Flipped to true once the sending domain is onboarded to Email Service
      // — until then a verification mail could never reach a real user.
      requireEmailVerification: false,
      sendResetPassword: async ({ user, url }) => {
        await sendMail(
          env,
          user.email,
          'Reset your PetPomo password',
          `Reset your password:\n\n${url}\n\nIf you didn't ask for this, ignore this email.`,
        );
      },
    },
    emailVerification: {
      sendVerificationEmail: async ({ user, url }) => {
        await sendMail(
          env,
          user.email,
          'Verify your PetPomo email',
          `Confirm this address belongs to you:\n\n${url}\n\nIf you didn't create a PetPomo account, ignore this email.`,
        );
      },
    },

    socialProviders: google,

    // better-auth's own limiter (per-path, e.g. sign-in at 3 req/10 s),
    // backed by the same KV. In-memory storage is useless across isolates,
    // so without KV it stays off and the D1 bumpLimit patterns still apply.
    rateLimit: env.KV_SESSIONS ? { enabled: true, storage: 'secondary-storage' as const } : undefined,

    advanced: {
      useSecureCookies: origin.startsWith('https://'),
    },

    plugins: [
      // role / banned / banReason / banExpires on user; ban checks on sign-in.
      admin(),
      // Turnstile on sign-up / sign-in / reset. Registered only when the
      // secret exists, mirroring turnstileOk() for /api/ask: unset = local
      // dev or a deliberate off-switch, and auth keeps working without it.
      ...(env.TURNSTILE_SECRET
        ? [captcha({ provider: 'cloudflare-turnstile', secretKey: env.TURNSTILE_SECRET })]
        : []),
    ],
  });
}

/**
 * Memoized per isolate. Bindings are stable for an isolate's lifetime, so
 * building the instance once per isolate (not per request) is safe and skips
 * re-parsing the config on every call.
 */
let cached: ReturnType<typeof buildAuth> | undefined;

export function getAuth(env: AuthBindings): ReturnType<typeof buildAuth> {
  return (cached ??= buildAuth(env));
}

/** What the session endpoints expose of a user — all this Worker needs. */
export interface AuthedUser {
  id: string;
  email: string;
  name?: string | null;
  role?: string | null;
  emailVerified?: boolean;
}
