/**
 * Regenerates worker/src/blogSlugs.ts — the allowlist of comment targets.
 *
 * A comment names the page it belongs to (`target`), and the Worker refuses
 * any target that is not a real page: without this, the moderation queue
 * could be filled with comments on pages that do not exist. The list is the
 * blog content folder's filenames plus the literal 'home' (the landing page),
 * frozen at build time — the same technique astro.config.mjs uses for
 * redirects.
 *
 * Runs automatically as part of `npm run build`; run it by hand after adding
 * a post if you need the worker list without a site build.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const posts = readdirSync(`${root}/src/content/blog`)
  .filter((f) => /\.(md|mdx)$/.test(f))
  .map((f) => f.replace(/\.(md|mdx)$/, ''))
  .sort();

const out = `/**
 * GENERATED by scripts/make-slugs.mjs as part of \`npm run build\` — do not
 * edit by hand. The allowlist of comment targets: every blog slug plus
 * 'home'. See that script's header for why the worker refuses anything else.
 */
export const COMMENT_TARGETS: ReadonlySet<string> = new Set([
  'home',
${posts.map((s) => `  ${JSON.stringify(s)},`).join('\n')}
]);
`;

writeFileSync(`${root}/worker/src/blogSlugs.ts`, out);
console.log(`blogSlugs.ts: ${posts.length} posts + 'home'`);
